Ostorlab/KEV

- nuclei/CVE-2023-4966.yaml
Existing template was found unreliable, I write my own template instead
> Add detection for CVE-2023-4966

- README.md
- agent_group.yaml
- nuclei/CVE-2023-1671.yaml
> CVE-2023-1671

- README.md
- agent_group.yaml
- nuclei/CVE-2023-47246.yaml
> CVE_2023_47246 SysAid

- README.md
- agent_group.yaml
- Fix args for proxylogon
- Exclude printnightmare (requires a srvhost)
> Fixes: proxylogon & printnightmare

- README.md
- agent_group.yaml
- nuclei/CVE-2023-29357.yaml
Tested on a live target ✅
<br>
> Add detection for Sharepoint CVE-2023-29357

- README.md
- agent_group.yaml
- nuclei/CVE-2023-6553.yaml
> Add detection for CVE-2023-6553

- README.md
- agent_group.yaml
- nuclei/CVE-2023-49103.yaml
> Add detection for CVE-2023-49103

- README.md
- agent_group.yaml
- nuclei/CVE-2023-41266.yaml
> Add detection for CVE-2023-41266

- README.md
- agent_group.yaml
- nuclei/CVE-2020-29557.yaml
> Add detection for CVE-2020-29557

- README.md
- agent_group.yaml
- nuclei/CVE-2023-2780.yaml
> Add detection for CVE-2023-2780

- README.md
- agent_group.yaml
- nuclei/CVE-2012-3152.yaml
Tested on multiple live instances
> Replace CVE-2012-3152

- README.md
- nuclei/CVE-2019-18935.yaml
> Update exploit for CVE-2019-18935

- README.md
- agent_group.yaml
- nuclei/CVE-2023-49070.yaml
> Add detection for CVE-2023-49070

- README.md
- agent_group.yaml
- nuclei/CVE-2023-51467.yaml
> Add detection for: CVE-2023-51467

- README.md
- agent_group.yaml
- nuclei/CVE-2023-47565.yaml
> CVE 2023 47565

- README.md
- agent_group.yaml
- nuclei/CVE-2023-27524.yaml
> Add detection for: CVE-2023-27524

- README.md
- agent_group.yaml
- nuclei/CVE-2023-46805.yaml
Reproduced on a live instance ✅
> Add detection for CVE-2023-46805

- README.md
- agent_group.yaml
- nuclei/CVE-2024-21887.yaml
Reproduced on a live instance ✅
> Add detection for CVE-2024-21887

- README.md
- agent_group.yaml
Did not find a target to reproduce the vulnerability ❌
> Add detection for CVE-2016-20017

- README.md
- agent_group.yaml
- nuclei/CVE-2023-7028.yaml
Reproduced on a live instance ✅
> Add detection for: CVE-2023-7028

- README.md
- agent_group.yaml
- nuclei/CVE-2023-22527.yaml
> Add detection for CVE-2023-22527

- README.md
Update description for:
- CVE-2023-6549
- CVE-2023-6549
> Update readme table

- README.md
- agent_group.yaml
- nuclei/CVE-2024-23897.yaml
> Add CVE-2024_23897 template

- README.md
Update description for:
- CVE-2024-21619
- CVE-2024-21620
- CVE-2024-21733
> Update Readme with new entries

- README.md
[preview_readme.webm](https://github.com/Ostorlab/KEV/assets/144700714/478353ad-aa8c-4c34-be14-207a4727b71a)
> Show Demos in README.md

- README.md
- nuclei/CVE-2024-1709.yaml
- Add detection for CVE-2024-21410
- Update CVE-2023-43770 description
> Add detection for CVE-2024-21410

- README.md
- Update description for CVE-2024-21413
- Fix wrong CVE ID for CVE-2024-1709
> Add description for CVE-2024-21413

- README.md
- agent_group.yaml
- nuclei/CVE-2024-1212.yaml
> Add detection for CVE-2024-1212

- README.md
- agent_group.yaml
- nuclei/CVE-2022-0412.yaml
> Add detection for CVE-2022-0412

- README.md
- agent_group.yaml
- nuclei/CVE-2019-7256.yaml
> Add detection for CVE-2019-7256

- README.md
- nuclei/CVE-2024-3400.yaml
> Add detection for CVE-2024-3400

- README.md
- agent_group.yaml
- nuclei/CVE-2023-43208.yaml
- nuclei/CVE-2024-4956.yaml
> Add nuclei templates for CVE-2024-4956 , CVE-2023-43208

- README.md
- agent_group.yaml
- nuclei/CVE-2024-23692.yaml
> Add CVE-2024-23692

- README.md
- agent_group.yaml
- nuclei/CVE-2024-28995.yaml
> Add CVE-2024-28995

- README.md
- agent_group.yaml
- nuclei/CVE-2024-4879.yaml
> Add a custom nuclei template for cve-2024-4879

- README.md
- agent_group.yaml
- nuclei/CVE-2024-7593.yaml
- Added CVE-2024-7593 nuclei template
- Added it to KEV and the agent group
> Add CVE-2024-7593

- README.md
- agent_group.yaml
- nuclei/CVE-2024-20440.yaml
Still didn't find a vulnerable instance
> Add detection for CVE-2024-20440

- README.md
- agent_group.yaml
- nuclei/CVE-2024-6670.yaml
Didn't find a vulnerable target but it does the same as the original poc
> Add detection for CVE-2024-6670

- README.md
> Add CVE-2020-14644

- README.md
- agent_group.yaml
- nuclei/CVE-2024-47176.yaml
This PR is for adding CVE-2024-47176 nuclei template
> add CVE-2024-47176 nuclei template

- README.md
- agent_group.yaml
- nuclei/CVE-2024-45519.yaml
> Add CVE-2024-45519

- README.md
- agent_group.yaml
- nuclei/CVE-2024-9463.yaml
- nuclei/CVE-2024-9465.yaml
Add Palo Alto CVEs and Fortinet CVE to KEV.
I'll try to Test it against real targets Once I find them.
> Add Palo Alto CVEs and Fortinet CVE to KEV.

- README.md
Add CVE-2024-9487 to the KEV table
> Add CVE-2024-9487

- README.md
- agent_group.yaml
- nuclei/CVE-2024-28987.yaml
> CVE-2024-28987

- README.md
Add CVE-2024-9164 to the KEV Table
> Add CVE-2024-9164 to the KEV Table

- README.md
> Add CVE-2024-9634 (Don't Merge Until Detection Is Merged)

- README.md
- agent_group.yaml
- nuclei/cyberpanel-rce.yaml
> Add cyberpanel-rce detection

- README.md
Add CVE-2024-50550 to the KEV table
The detection PR: https://github.com/Ostorlab/agent_asteroid/pull/129
> Add CVE-2024-50550 to the KEV table

- README.md
- agent_group.yaml
- nuclei/CVE-2024-5910.yaml
> Add CVE-2024-5910

- README.md
- agent_group.yaml
- nuclei/CVE-2021-26086.yaml
> Add CVE-2021-26086

- README.md
Add CVE-2019-16278 to the KEV table
> Add CVE-2019-16278 to the KEV table

- README.md
- agent_group.yaml
- nuclei/CVE-2024-38812.yaml
> Add CVE-2024-38812

- README.md
- agent_group.yaml
- nuclei/CVE-2024-0012.yaml
None of the targets tested is vulnerable
> Add CVE-2024-0012 detection

- README.md
- agent_group.yaml
- nuclei/CVE-2024-45507.yaml
> Add CVE-2024-45507

- README.md
- agent_group.yaml
- nuclei/CVE-2024-11680.yaml
> Add CVE-2024-11680

- README.md
- agent_group.yaml
- nuclei/CVE-2024-10914.yaml
No vulnerable targets were found so far.
> Add CVE-2024-10914

- README.md
- agent_group.yaml
- nuclei/CVE-2024-46938.yaml
The template is based on the research done by [Assetnote](https://www.assetnote.io/resources/research/leveraging-an-order-of-operations-bug-to-achieve-rce-in-sitecore-8-x---10-x). 
Couldn't find any vulnerable targets on the first 2 pages of Shodan and Fofa
> Add Detection For CVE-2024-46938

- README.md
- agent_group.yaml
- nuclei/CVE-2024-41713.yaml
> Add Detection for CVE-2024-41713

- README.md
- agent_group.yaml
- nuclei/CVE-2024-12209.yaml
This PR is for adding Nuclei template for CVE-2024-12209
PS: The template is still a PR by the time i am making this PR(https://github.com/projectdiscovery/nuclei-templates/pull/11321)
**AND WE FOUND NO VULNERABLE TARGETS**
> Add nuclei template for CVE-2024-12209

- README.md
- agent_group.yaml
- nuclei/CVE-2024-8963.yaml
- We had a Patch-Date based detection for `CVE-2024-8963` but now that an exploit is present I modified it.
> Add Detection for CVE-2024-8963 and Add CVE-2024-11639 to KEV

- README.md
- agent_group.yaml
- nuclei/CVE-2024-36404.yaml
I didn't find vulnerable instances online.
> Add Detection for CVE-2024-36404 and Add CVE-2023-34990 and CVE-2024-51479 to KEV

- README.md
- agent_group.yaml
- nuclei/CVE-2024-43919.yaml
> Add Detection for CVE-2024-43919.

- README.md
- agent_group.yaml
- nuclei/CVE-2024-52875.yaml
> Add Detection for CVE-2024-52875

- README.md
- agent_group.yaml
- nuclei/CVE-2024-12987.yaml
No vulnerable target was found on the web search engines. but the template is inspired from the following [research](https://netsecfish.notion.site/Command-Injection-in-apmcfgupload-endpoint-for-DrayTek-Gateway-Devices-1676b683e67c8040b7f1f0ffe29ce18f)
> [Feature](os-14272) Add Detection for CVE-2024-12987

- README.md
- agent_group.yaml
- nuclei/CVE-2024-45195.yaml
Couldn't find a vulnerable target in the first 2 pages of Shodan or Fofa
> Add Detection for CVE-2024-45195

- README.md
- agent_group.yaml
- nuclei/CVE-2024-53704.yaml
> Add Detection for CVE-2024-53704

- README.md
- agent_group.yaml
- nuclei/CVE-2022-47945.yaml
- No online vulnerable targets were found when testing the template.
> Add Detection for CVE-2022-47945

- .github/workflows/lint-pr.yml
This PR adds the semantic-pull-request GitHub Action to enforce Conventional Commits formatting for PR titles.
**Key Features**:
- Provides automated validation of PR titles
- Supports [WIP] prefix for work in progress
The action validates PR titles against patterns like: feat:, fix:, docs:, refactor:, test:, ci:, chore:
**Action**: https://github.com/amannn/action-semantic-pull-request
> feature: Add semantic-pull-request GitHub Action `KEV`

- README.md
- agent_group.yaml
- nuclei/CVE-2025-27636-29891.yaml
> feature: Add Detection for CVE-2025-27636 and CVE-2025-29891

- README.md
- agent_group.yaml
- nuclei/CVE-2024-13160.yaml
- The template implements the same logic used in the [PoC](https://www.horizon3.ai/attack-research/attack-blogs/ivanti-endpoint-manager-multiple-credential-coercion-vulnerabilities/).
> feature: Add Detection for CVE-2024-13160

- README.md
- agent_group.yaml
- nuclei/CVE-2025-24813.yaml
> feature: Add Detection for CVE-2025-24813

- nuclei/CVE-2022-43939.yaml
Missing matchers condition.
Good catch @deadly-panda
> fix: Update CVE-2022-43939.yaml

- README.md
- agent_group.yaml
- nuclei/CVE-2025-1974.yaml
> feature: Add Detection for CVE-2025-1974

- README.md
- agent_group.yaml
- nuclei/CVE-2024-48248.yaml
> feature: Add Detection for CVE-2024-48248

- README.md
- agent_group.yaml
- nuclei/CVE-2025-28367.yaml
Tested on bunch of targets:
Response from non-vulnerable targets:
Response from a vulnerable target:
> feature: Add Detection for CVE-2025-28367

- README.md
- agent_group.yaml
- nuclei/CVE-2017-12637.yaml
> feature: Add Detection for CVE-2017-12637

- README.md
- agent_group.yaml
- nuclei/CVE-2025-32432.yaml
> feature: Add Detection for CVE-2025-32432

- README.md
- agent_group.yaml
- nuclei/CVE-2025-34028.yaml
> feature: Add Detection for CVE-2025-34028

- README.md
- agent_group.yaml
- nuclei/CVE-2025-4427.yaml
**Add Detection for Unauthenticated Remote Code Execution in Ivanti EPMM (CVE-2025-4427 & CVE-2025-4428)**
This PR adds a detection template targeting an unauthenticated RCE vulnerability in Ivanti EPMM, leveraging EL Injection in Bean Validation.
- ✅ **Tested against 500+ non-vulnerable websites** with zero false positives observed.
- 🎯 **Successfully identified a vulnerable Ivanti EPMM instance** during testing across multiple targets.
> feature: Add Detection for CVE-2025-4427.

- README.md
- agent_group.yaml
- nuclei/CVE-2017-8046.yaml
```
[INF] [CVE-2017-8046] Dumped HTTP request for http://localhost:8080
GET / HTTP/1.1
Host: localhost:8080
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36 Edg/121.0.0.0
Connection: close
Accept: */*
Accept-Language: en
Accept-Encoding: gzip
[DBG] [CVE-2017-8046] Dumped HTTP response http://localhost:8080
HTTP/1.1 200 
Connection: close
Transfer-Encoding: chunked
Content-Type: application/hal+json;charset=UTF-8
Date: Sat, 31 May 2025 16:23:38 GMT
{
"_links" : {
"entity" : {
"href" : "http://localhost:8080/entity{?page,size,sort}",
"templated" : true
},
"profile" : {
"href" : "http://localhost:8080/profile"
}
}
}
[INF] Using Interactsh Server: oast.fun
[INF] [CVE-2017-8046] Dumped HTTP request for …
```
> feature: Add detection of CVE-2017-8046.

- README.md
> fix: order of cves
